version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: no
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
